version: "2"
services:
  world-1:
    image: dstacademy/dontstarvetogether
    container_name: world-1
    hostname: world-1
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: world-1.env
    ports:
      - "10999:10999/udp"
    volumes:
      - ./world-1:/var/lib/dsta/cluster

  world-2:
    image: dstacademy/dontstarvetogether
    container_name: world-2
    hostname: world-2
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: world-2.env
    ports:
      - "11000:10999/udp"
    volumes:
      - ./world-2:/var/lib/dsta/cluster

  world-3:
    image: dstacademy/dontstarvetogether
    container_name: world-3
    hostname: world-3
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: world-3.env
    ports:
      - "11001:10999/udp"
    volumes:
      - ./world-3:/var/lib/dsta/cluster
