version: "2"
services:
  world:
    image: dstacademy/dontstarvetogether
    container_name: world
    tty: true
    stdin_open: true
    ports:
      - "10999:10999/udp"
    environment:
      - SERVER_TOKEN: your-server-token
