version: "2"
services:
  world:
    image: dstacademy/dontstarvetogether
    container_name: world
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    ports:
      - "10999:10999/udp"
    environment:
      - TOKEN: your-server-token
